detectNetworkCondition:
  no

userAgent:
  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36

captureScreenAutomatically:
  no

viewportSize:
  width: 1366
  height: 768

username:
  iamyourfather@holyfield.com

password:
  topsecret

courses:
  - https://www.lynda.com/Photoshop-tutorials/Automatic-BrightnessContrast/373100/427042-4.html
  - https://www.lynda.com/JavaScript-tutorials/JavaScript-validation-troubleshooting/574716/612093-4.html
  - dirName: Excel
    startPoint: https://www.lynda.com/Excel-tutorials/Exploring-Page-Layout-tab-view/116478/125049-4.html

intervalBetweenTutorialVisits:
  20
